name: Create Release Note

on:
  pull_request:
    # PRが閉じたタイミングで実行
    types:
      - closed
    # mainブランチのみを対象とする
    branches:
      - main

jobs:
  build-and-release:
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: npm ci

      - name: build dependencies
        run: npm run build
      
      - name: Delete unnecessary files
        run: |
          rm esbuild.js
          rm -r src
          rm tsconfig.json
          rm README.md
      - name: Inspect files after checkout
        run: ls

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
